# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eZ263gDN1jfkRbMxlsCDv2NEZovUvrpw
"""

print("hell world")
print("test google classroom")