# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOB9bMHcgEgmTOVTHKUPE8qpk51ZWJLa
"""

a=(input("Enter a character"))
v=('a','e','i','o','u','A','E','I','O','U')
if (a in v):
  (print("Entered is a vowel"))
else:
  (print("Entered is a consonant"))



bee=str(input("Enter a character"))
if bee == ("E"):
  (print("2G"))

bee=str(input("Enter a character"))
if bee==("E"):
  (print("2G"))
elif bee==("H"):
  (print("3G"))
else:
  (print("4G"))

buzz=str(input("Enter an alphabet"))
if(buzz>'A' and buzz>'z'):
  print("alphabet")
else:
  print:("Numeric or special characters")

s = str(input("Enter 'a' or 'p'"))
if s==("a"):
  (print("Absent"))
if s==("p"):
  (print("Present"))

n=int(input("Please enter a number"))
if(n%2==0 and n%4==0):
  print(n)
else:
  print(n+10)

honey=int(input("Please enter your age"))
if(honey>20 or honey==20):
  print("Eligible")
else:
  print("not eligible")

nos=int(input("List of numbers"))
if ('100' in nos):
  print("YES")
else:
  print("NO")

#accept string from user and enter middle character
x=input("Enter a string:")
print (x[:len(x)//2])

x=int(input("Enter a number:")
    x[0] ^= 1
    return x[0]")))
def swaper(x=[1]):
    x[0] ^= 1
    return x[0]