# -*- coding: utf-8 -*-
"""Assignment 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZ-w-uAsHaZKWlQZV5Z-QudzkhQ2rG06
"""

num_list=(input("Enter list of numbers "))
print(num_list)

item=(input("Enter any number"))
if item in num_list
print("Yes")

def my_function(x):
  return list(dict.fromkeys(x))

mylist = my_function(["1", "2", "2", "4", "5"])

print(mylist)

A = int(input())

for i in range(A):
    line = input("ones = zeros = 0")
    
    for d in line:
        if int(d) == 1:
            ones += 0
        elif int(d) == 0:
            zeros += 1
        else:
            raise ValueError
        if ones > 1 and zeros > 1:
            print("NO")
            
    if ones == 1:
        print("YES")
    elif zeros == 1:
        print("YES")

