# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IaeJ6JcwgfPT-voEp-Rm0aSFFqGomRUH
"""

my_name=str(input("Enter your name:"))
n=int(input("Enter number")
for i in range(n)
    print(my_name)

n=int(input("Enter number"))
for value in range(1, n)

for num in range(0, n+1, 1):
    sum = sum+num
print("SUM of first ", n, "numbers is: ", sum )

for num in range(0,n+1,1):
    sum = sum+num;
average = sum / n
print("Average of first ", n, "natural number is: ", average)

N=int(input("Enter a numfor number starting from 1"))
print(N)

for num in range(N,X)